<?php

/**
 * @file
 * Contains jalur_prestasi.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jalur_prestasi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jalur_prestasi module.
    case 'help.page.jalur_prestasi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pilihan jalur prestasi') . '</p>';
      return $output;

    default:
  }
}
